default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: <%= ENV['FETCH_BOT_DATABASE_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: fetch_bot_development

test:
  <<: *default
  database: fetch_bot_test

production:
  <<: *default
  database: fetch_bot_production
